"""empty message

Revision ID: 344dcbe87c6d
Revises: 92b7c24334b3
Create Date: 2019-05-01 10:35:31.738862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344dcbe87c6d'
down_revision = '92b7c24334b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_name1', sa.String(length=50), nullable=False),
    sa.Column('part_no1', sa.String(length=20), nullable=False),
    sa.Column('supplier1', sa.String(length=50), nullable=False),
    sa.Column('sta1', sa.String(length=20), nullable=False),
    sa.Column('pm1', sa.String(length=20), nullable=False),
    sa.Column('project1', sa.String(length=20), nullable=False),
    sa.Column('ls_time1', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_apqp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sko_date', sa.String(length=50), nullable=False),
    sa.Column('sko_output', sa.String(length=50), nullable=False),
    sa.Column('ftf_date', sa.String(length=50), nullable=False),
    sa.Column('ftf_output', sa.String(length=50), nullable=False),
    sa.Column('ott_date', sa.String(length=50), nullable=False),
    sa.Column('ott_output', sa.String(length=50), nullable=False),
    sa.Column('ots_date', sa.String(length=50), nullable=False),
    sa.Column('ots_output', sa.String(length=50), nullable=False),
    sa.Column('tto_date', sa.String(length=50), nullable=False),
    sa.Column('tto_output', sa.String(length=50), nullable=False),
    sa.Column('psw_date', sa.String(length=50), nullable=False),
    sa.Column('psw_output', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telephone', sa.String(length=11), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('part_apqp')
    op.drop_table('part')
    # ### end Alembic commands ###
