"""empty message

Revision ID: 6a865fbdaa09
Revises: fea1cfa3020e
Create Date: 2019-04-28 22:18:52.453202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a865fbdaa09'
down_revision = 'fea1cfa3020e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_name1', sa.String(length=50), nullable=False),
    sa.Column('part_no1', sa.String(length=20), nullable=False),
    sa.Column('supplier1', sa.String(length=50), nullable=False),
    sa.Column('sta1', sa.String(length=20), nullable=False),
    sa.Column('pm1', sa.String(length=20), nullable=False),
    sa.Column('project1', sa.String(length=20), nullable=False),
    sa.Column('ls_time1', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('part')
    # ### end Alembic commands ###
