"""empty message

Revision ID: 92b7c24334b3
Revises: 6a865fbdaa09
Create Date: 2019-05-01 09:50:19.320720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b7c24334b3'
down_revision = '6a865fbdaa09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part_apqp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sko_date', sa.String(length=50), nullable=False),
    sa.Column('sko_output', sa.String(length=50), nullable=False),
    sa.Column('ftf_date', sa.String(length=50), nullable=False),
    sa.Column('ftf_output', sa.String(length=50), nullable=False),
    sa.Column('ott_date', sa.String(length=50), nullable=False),
    sa.Column('ott_output', sa.String(length=50), nullable=False),
    sa.Column('ots_date', sa.String(length=50), nullable=False),
    sa.Column('ots_output', sa.String(length=50), nullable=False),
    sa.Column('tto_date', sa.String(length=50), nullable=False),
    sa.Column('tto_output', sa.String(length=50), nullable=False),
    sa.Column('psw_date', sa.String(length=50), nullable=False),
    sa.Column('psw_output', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('part_apqp')
    # ### end Alembic commands ###
