"""empty message

Revision ID: fea1cfa3020e
Revises: dee2bd485a4e
Create Date: 2019-04-28 21:44:22.345798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea1cfa3020e'
down_revision = 'dee2bd485a4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_name1', sa.String(length=50), nullable=False),
    sa.Column('part_no1', sa.String(length=20), nullable=False),
    sa.Column('supplier1', sa.String(length=50), nullable=False),
    sa.Column('sta1', sa.String(length=20), nullable=False),
    sa.Column('pm1', sa.String(length=20), nullable=False),
    sa.Column('project1', sa.String(length=20), nullable=False),
    sa.Column('ls_timei1', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('part')
    # ### end Alembic commands ###
